apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-front-ordemservico-deployment
spec:
    selector:
        matchLabels:
            name: ordem-servico-front
    template:
        metadata:
            labels:
                name: ordem-servico-front
        spec:
            containers:
                - name: container-ordem-servico-front
                  image:  osdeni/osdeni-ordem-servico-vue:v6
                  ports:
                    - containerPort: 80