apiVersion: v1
kind: Pod
metadata:
  name: ordem-servico-front
spec:
  containers:
    - name: container-ordem-servico-front
      image: osdeni/osdeni-ordem-servico-vue:v6
      ports:
        - containerPort: 80