apiVersion: v1
kind: Service
metadata:
  name: servico-api-ordemservico
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      nodePort: 30002
  selector:
    name: ordem-servico-api